# Generated by Django 3.0.3 on 2022-04-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0003_auto_20220408_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
